learning_users/basic_app/urls.py
from django.urls import path
from  .import views

app_name='basic_app'


urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),


    path('org/',views.org_base,name='org_base'),
    path('orgname/',views.orgname,name='orgname'),
    path('team/',views.Team_dic,name='Team_dic'),
    path('agile/',views.agile,name='agile'),
    path('emp/',views.emp,name='emp'),


]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    #path('org/',include('basic_app.urls_org')),

]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)


    #addition by SIVA

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)


    def __str__(self):
        return self.user.username


class Organization(models.Model):
    orgname = models.CharField(max_length = 100, blank=True)

    def __str__(self):
        return str(self.orgname)

class Team(models.Model):
    teamID = models.AutoField(primary_key=True)
    teamName = models.CharField(max_length = 100, blank=True)
    org = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.teamName)

class AgileTeam(models.Model):
    agileTeamID = models.AutoField(primary_key=True)
    agileTeamName = models.CharField(max_length = 100, blank=True)
    org = models.ForeignKey(Organization, on_delete=models.CASCADE)
    team = models.ForeignKey(Team,  on_delete=models.CASCADE)

    def __str__(self):
        return str(self.agileTeamName)

class Employee(models.Model):
    name = models.CharField(max_length=100)
    assoc_id = models.CharField(max_length=10)
    username = models.CharField(max_length=50, blank=True)
    password = models.CharField(max_length=50, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    agile_team = models.ForeignKey(AgileTeam, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo,Organization, Team, AgileTeam, Employee

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

class OrganizationForm(forms.ModelForm):
    class Meta():
        model = Organization
        fields = ('orgname',)

class TeamForm(forms.ModelForm):
    class Meta():
        model = Team
        fields = ('teamName','org')


class AgileTeamForm(forms.ModelForm):
    class Meta():
        model = AgileTeam
        fields = '__all__'

class EmployeeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(render_value = True))
    class Meta:
        model = Employee
        fields = ('name', 'assoc_id', 'username', 'password', 'organization', 'team', 'agile_team',)
        labels = {
            'name':'Name',
            'assoc_id':'Associate ID',
            'username': 'Username',
            'password': 'Password',
            'organization':'Organization Name',
            'team': 'Team Name',
            'agile_team': 'Agile Team'
        }

        def __init__(self, *args, **kwargs):
            super(EmployeeForm,self).__init__(*args, **kwargs)
        # Code to make fields optional and to set the first option of dropdown as "Choose.."
            self.fields['organization'].required = False
            self.fields['organization'].empty_label = "Choose.."
            self.fields['team'].required = False
            self.fields['team'].empty_label = "Choose.."
            self.fields['agile_team'].required = False
            self.fields['agile_team'].empty_label = "Choose.."

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm,EmployeeForm,OrganizationForm,TeamForm,AgileTeamForm

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
#from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse('You are logged in , Nice !')

def register(request):
    registered=False
    print("..................................................................")
    if request.method=='POST':
        print(request.method)
        user_form=  UserForm(data=request.POST)
        profile_form= UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()
            print(user+"user is valid................")
            profile=profile_form.save(commit=False)
            profile.user=user
            print(user+"profile.user.....................")
            if 'profile_pic' in request.FILES:
                profile.profile_pic= request.FILES['profile_pic']

            profile.save()
            print(profile+"profile details.................")
            registered=True
        else:
            print("Error details in user and profile............")
            print(user_form.errors , profile_form.errors)

    else:
        print("not post method(get method )............. ")
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basic_app/Registration.html',{
    'user_form':user_form,
    'profile_form':profile_form,
     'registered':registered
     }
     )

def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('AACOUTN IS NOT ACTIVE!')

        else:
            print("some ont try to login failed")
            print('username :{} and password :{}'.format(username,password))
            return HttpResponse("invalid login details  suppiled")

    else:
        return render(request,'basic_app/login.html',{})


def org_base(request):
    return render(request,'org/org_base.html')

def orgname(request):
    if request.method == 'POST':
        orgName= OrganizationForm(data=request.POST)
        if orgName.is_valid:
            orgName.save()
    return render(request,'org/orgName.html',{'org_name':OrganizationForm})


def Team_dic(request):
    if request.method == 'POST':
        team= TeamForm(data=request.POST)
        if team.is_valid:
            team.save()
    return render(request,'org/team.html',{'team_me':TeamForm})


def agile(request):
    if request.method == 'POST':
        agile=AgileTeamForm(data = request.POST)
        if agile.is_valid:
            agile.save()
        else:
            print(agile.errors)
    else:
        print('NOT POST METHOD IN AGILE')
        agile = AgileTeamForm

    return render(request,'org/agile.html',{'agile':agile})


def emp(request):
    if request.method == 'POST':
        emp = EmployeeForm(data = request.POST)
        if emp.is_valid:
            emp.save()
        else:
            print(emp.errors)

    else:
        emp=EmployeeForm
    return render(request,'org/emp.html',{'emp':emp})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav>
      <div class="">
        <ul>
          <li><a href="{% url 'index' %}">Home index</a></li>
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
          <li><a href="{% url 'basic_app:register' %}">Register</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Login</a></li>

          {% else %}
          <li><a href="{% url 'basic_app:login' %}">Login</a></li>

          {% endif %}

          
          <li><a href="{% url 'basic_app:org_base' %}">ORG</a></li>
          <li><a href="{% url 'basic_app:orgname' %}">Orgname</a></li>
          <li><a href="{% url 'basic_app:Team_dic' %}">Team</a></li>
          <li><a href="{% url 'basic_app:agile' %}">Agile</a></li>
          <li><a href="{% url 'basic_app:emp' %}">EMP</a></li>



        </ul>
      </div>
    </nav>



    <div class="">
      {% block body_block %}
      <a href="basic_app/org"> ORGANIZATION </A>
      {% endblock %}

    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block body_block %}
<h1>index.html page</h1>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}


{% block body_block %}
<<h1> Please login here:</h1>

  <form action="{% url 'basic_app:login' %}" method="POST">
    
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username">
    <label for="password">Password</label>
    <input type="password" name="password">
    <<input type="submit" name="" value="Login">
  </form>

{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}

{% load static %}


{% block body_block %}
<div class="">
  {% if registered %}
  <h1>Thank you for Registering </h1>

  {% else %}
  <h1>Registration Here</h1>
  <h3>fill the form:<h3/>


  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}


    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}
</div>

{% endblock %}

learning_users/templates/org/agile.html
{% extends "basic_app/base.html" %}

{% block body_block %}
<h2>Please Enter AgileTeam Details:</h2>

<form class=""  method="POST">
  {{agile}}
  {% csrf_token %}
  <input type="submit" name="agile" value="save">
</form>
<li><a href="{% url 'index' %}"><< Home index</a></li>

{% endblock %}

learning_users/templates/org/emp.html
{% extends "basic_app/base.html" %}

{% block body_block %}
<h2>Please Enter EMP Details:</h2>

<form class=""  method="post">
  {{emp}}

  {% csrf_token %}
  <input type="submit" name="emp" value="save">
</form>

{% endblock %}

learning_users/templates/org/orgName.html
{% extends 'basic_app/base.html' %}

    {% block body_block %}
    <h2>Please Enter Organization details:</h2>
    <form class=""  method="post">
      {{org_name}}


      {% csrf_token %}
      <input type="submit" name="orgName" value="save">
    </form>

    {% endblock %}

learning_users/templates/org/org_base.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>WELLCOOME TO ORGANIZATION</h1>
<ul>
  <li><a href="{% url 'basic_app:register' %}">Register</a></li>
  <li><a href="{% url 'index' %}">Home index</a></li>
  <li><a href="{% url 'basic_app:orgname' %}">orgname</a></li>

</ul>
{% endblock %}

learning_users/templates/org/team.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
<h1>Please Enter Team Detais:</h1>

<form class=""  method="post">
  {{team_me}}
  {% csrf_token %}
  <input type="submit" name="team" value="save">
</form>
{% endblock %}